server:
  port: 8080

spring:
  application:
    name: spring-boot-sse-test
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:sse-test
logging:
  level:
    org:
      springframework:
        jdbc:
          core: DEBUG
